In [ ]:
import tensorflow as tf

import os
import tensorflow_datasets as tfds
import numpy as np
from PIL import Image

import matplotlib.pyplot as plt
import matplotlib.patches as patches

In [ ]:
f = open("train.txt")
texts = f.readlines()
Xs = []  
Ys = []
for i in range(len(texts)):
  x,y = texts[i].strip().split(";")
  if y == "surprise":
    print("surprise")
    continue
  Xs.append(x)
  Ys.append(y)
f.close()

surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
surprise
s

In [ ]:
labels = []
for i in Ys:
  if not i in labels:
    labels.append(i)

In [ ]:
labels

['sadness', 'anger', 'love', 'fear', 'joy']

In [ ]:
PN = [0, 0, 1, 0, 1]

In [ ]:
tmp_Ys = []
for i in Ys:
  if PN[labels.index(i)] != -1:
    tmp_Ys.append(PN[labels.index(i)])
  else:
   print("OOBA!")

In [ ]:
Ys = np.array(tmp_Ys)

In [ ]:
# tokenlize
token_to_word = {}
word_to_token = {}
token = 1 #0 is for padding
for i in Xs:
  for word in i.split(" "):
    if not word in word_to_token:
      token_to_word[token] = word
      word_to_token[word] = token
      token+=1

tmp_Xs = []
for i in Xs:
  row = []
  for word in i.split(" "):
    row.append(word_to_token[word])
  tmp_Xs.append(row)

In [ ]:
# padding
maxlen = 0
for i in tmp_Xs: #not Xs
  maxlen = max(len(i),maxlen)

Xs = []
for i in tmp_Xs:
  l = len(i)
  more = maxlen - l
  z = np.zeros(shape=more)
  Xs.append(np.append(z,i))
Xs = np.array(Xs)

In [ ]:
model = tf.keras.models.Sequential([
tf.keras.layers.Embedding(len(token_to_word)+1,128,input_length=maxlen), #hlkunmmshidimaayunyanghuiqukanzhiqiandecaizhi
tf.keras.layers.GRU(100, activation='relu', return_sequences=1),
tf.keras.layers.Dense(50, activation='relu'),
tf.keras.layers.Dropout(0.7),
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(200, activation='relu'),
tf.keras.layers.Dense(30, activation='relu'),
tf.keras.layers.Dense(20, activation='relu'),
tf.keras.layers.Dense(10, activation='relu'),
tf.keras.layers.Dense(1,activation="sigmoid"),
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/
])

model.summary()
# print(model.output_shape)
model.compile(optimizer=tf.keras.optimizers.Adam(),
          loss='binary_crossentropy',metrics=["accuracy"])


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 66, 128)           1909504   
                                                                 
 gru_8 (GRU)                 (None, 66, 100)           69000     
                                                                 
 dense_55 (Dense)            (None, 66, 50)            5050      
                                                                 
 dropout_8 (Dropout)         (None, 66, 50)            0         
                                                                 
 flatten_8 (Flatten)         (None, 3300)              0         
                                                                 
 dense_56 (Dense)            (None, 200)               660200    
                                                                 
 dense_57 (Dense)            (None, 30)               

In [ ]:
model.fit(Xs, Ys, epochs = 3, validation_split=0.01)

In [ ]:
def predict(sen):
  a = []
  sen = sen.replace(",","").replace(".","").replace("!","").replace("?","").replace("'","")
  # print(sen)#kunttkouke zhelibugaidehua sihu buhuqidong !
  for i in sen.split(" "):#xiamiayangyueixnyiweiwnagisplityewnaglelowerexexex
    try:
      a.append(word_to_token[i.lower()])
    except:
      print("Warning: %s is not found" % i)
      a.append(-1)
  a = np.append(a, np.zeros(shape=(maxlen-len(a))))
  return model.predict(np.array([a]))

  return labels[np.argmax(model.predict(np.array([a])))]

In [ ]:
predict("You are so cool")

array([[0.52711195]], dtype=float32)

In [ ]:
predict("I am so happy")

array([[0.52635854]], dtype=float32)

In [ ]:
#koukshouyangkunttsuan zhege dictmieyouxkoukunkk

In [ ]:
predict("I don't want to be at the mercy of my emotions I want to use them to enjoy them and to dominate them")

array([[0.7133436]], dtype=float32)

In [ ]:
predict("Today I went to a store and they forgot to put sugar in my drink, I will never go there again")

array([[0.7764932]], dtype=float32)

In [ ]:
predict("It has been a long day and I am so moved when my grilfriend picked me up from work")

In [ ]:
predict("i feel strong and good overall")

In [ ]:
token_to_word[0] = ""

In [ ]:
string = ""
for i in Xs[0]:
  if i==0:
    break
  print(token_to_word[int(i)])
  string+=token_to_word[int(i)]+" "
predict(string)

In [ ]:
labels[np.argmax(Ys[0])]

In [ ]:
string

In [ ]:
model.save("model")
!zip model.mod model -r

In [ ]:
!cp model.mod drive/MyDrive/NLPCS310.mod